apiVersion: v1
kind: Secret
metadata:
  name: workload-secrets-data
  namespace: tap-install
type: Opaque
stringData:
  content.yaml: |
    git:
      host: <git host>
      username: <git username>
      token: <git token>
      docker: <dockerconfigjson from registry-secret in tap-install>