#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #@ data.values.imported.secret-data.dockerdata