#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: #@ data.values.imported.registry.dockerconfigjson