#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  annotations:
    tekton.dev/git-0: #@ data.values.imported.secret-data.host 
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.imported.secret-data.username
  password: #@ data.values.imported.secret-data.token